### ISSUE TITLE
Issue with dtype in many examples

### ISSUE THREAD

**Issue by aarobel** [zwicker-group/py-pde#128]
Hello,
I am just getting started with py-pde, I am attempting to go through many of the examples. I did a clean install on a fresh environment in conda, but I am getting a similar error on some, but not all the examples. Here is the error, for example on the "Simple Diffusion Equation" example:

`~/anaconda3/envs/pdeenv/lib/python3.7/site-packages/pde/fields/base.py in _apply_operator(self, operator, bc, out, label, **kwargs)
   1620             # apply the operator with boundary conditions
   1621             op_with_bcs = self.grid.make_operator(operator_info, bc=bc, **kwargs)
-> 1622             out.data[:] = op_with_bcs(self.data)
   1623 
   1624         return out

TypeError: expected dtype object, got 'numpy.dtype[float64]'`

**Comment by david-zwicker** [comment]
This is strange – I have never seen this error. Could you please run the [script `show_environment.py`](https://github.com/zwicker-group/py-pde/blob/master/scripts/show_environment.py) ([raw code](https://raw.githubusercontent.com/zwicker-group/py-pde/master/scripts/show_environment.py)) and copy the output here. This would give me more information about your setup.

**Comment by aarobel** [comment]
Here is the output: 

```
package version: 0.16.2
python version: 3.7.11 (default, Jul 27 2021, 07:03:16) 
    [Clang 10.0.0 ]
platform: darwin

config:
    numba.parallel_threshold: 65536
    numba.parallel: True
    numba.fastmath: True
    numba.debug: False

mandatory packages:
    matplotlib: 3.2.2
    numba: 0.50.1
    numpy: 1.21.2
    scipy: 1.5.1
    sympy: 1.8

matplotlib environment:
    backend: MacOSX
    plotting context: BasicPlottingContext

optional packages:
    h5py: not available
    napari: not available
    pandas: 1.0.5
    pyfftw: not available
    tqdm: 4.62.2

numba environment:
    version: 0.50.1
    parallel: True
    fastmath: True
    debug: False
    using_svml: False
    threading_layer: workqueue
    omp_num_threads: None
    mkl_num_threads: None
    num_threads: 4
    num_threads_default: 4
    cuda_available: False
    roc_available: False
```

**Comment by david-zwicker** [comment]
Thank you for the details! It looks as if you are using the latest version of numpy, which I couldn't test, yet. Since this version changed how dtypes are handled, the error could very well originate there. I'll hopefully find time soon to test the latest NumPy version and recreate your error.

**Comment by aarobel** [comment]
Thanks, I was able to avoid the issue by reverting my numpy version in the environment to 1.18

**Comment by david-zwicker** [comment]
My tests indicate that the problem disappeared with the latest numpy/numba packages, so I'll close this issue for now. Feel free to reopen if the problems persist, though.
