### ISSUE TITLE
Wave Equation Amplication Issue

### ISSUE THREAD

**Issue by MatthewBelzer** [zwicker-group/py-pde#15]
When I try to use the wave equation the amplitude of the wave is amplified by a lot over the duration of the simulation. Here is my code:

```
import numpy as np
from pde import FieldCollection
from pde import (DiffusionPDE, UnitGrid, ScalarField, MemoryStorage,
                 PlotTracker, PrintTracker, RealtimeIntervals, DataTracker)
from pde.visualization import movies
import math
import random
import pde
import pandas
import ffmpeg
import matplotlib.pyplot as plt; plt.rcdefaults()
import numpy as np
import matplotlib.pyplot as plt


storage = MemoryStorage()

trackers = [
    'progress',                    # show progress bar during simulation
    'steady_state',                # abort when steady state is reached
    storage.tracker(interval=1),   # store data every simulation time unit
    PlotTracker(show=True),        # show images during simulation
]

grid = pde.UnitGrid([64, 64])
field1 = ScalarField.random_uniform(grid, 0, 0)  # generate initial condition
field2 = ScalarField(grid);
field1.add_interpolated([48, 48], 1)
field1.add_interpolated([48,16], 1)
state = FieldCollection([field1,field2]); #first slot is the density field, 

eq = pde.WavePDE(speed=1);
result = eq.solve(state, t_range=200, dt=1, tracker = trackers)
result.plot(colorbar = True, show = True)       # plot the resulting field
movies.movie_multiple(storage, filename = r'C:\Users\matth\URECA Simulation\testfile.mp4')
```

[and here is the file of the movie](https://drive.google.com/file/d/1QFoU04SABiNWzISK25s5aGNiHcpQAy_V/view?usp=sharing). In the movie the colorbar is at 10^90 and the wave can only be seen at the end of the movie, which means that the amplitude is increasing throughout the simulation. I looked at the documentation and I am not sure why this is happening.

**Comment by david-zwicker** [comment]
Yes, this is an expected behavior for the simple explicit Euler method. In essence, the explicit method does not conserve the energy of the wave and every small deviation is amplified. This problem can be reduced by choosing smaller time steps and smaller wave speeds, but this will not fully remove the problem. One might get better results with an implicit method. The simplest implicit scheme is already implemented in `py-pde` and can be activated by using `method="implicit"` when calling `eq.solve`. Moreover, the solvers shipped with `scipy` are also supported, see `examples/solver_comparison.py`. However, they might be quite a bit slower since they are not compiled.

**Comment by pretentious7** [comment]
Does the implicit scheme use runge kutta?

**Comment by david-zwicker** [comment]
It uses the backward Euler method, which can be classified as a low order Runge-Kutta method.

**Comment by pretentious7** [comment]
Would a second order runge kutta be more computationally optimal in this case (wave simulation)? I'd be willing to try and implement it if so, would be fun to work with numba.

**Comment by david-zwicker** [comment]
I'm not an expert on these methods but I would certainly welcome pull requests that implement more general solvers. A good starting point would probably be to look at the implementations of `pde.solvers.implicit` and `pde.solvers.explicit`. I just realized that the explicit solver already supports Runge-Kutta 4/5, which is an explicit stepper. It would be great to have more methods available, either as extensions to the present solver classes or as a separate `RungeKuttaSolver` class.

**Comment by MatthewBelzer** [comment]
Thank you so much, it worked!

**Comment by david-zwicker** [comment]
Could you specify what you did to make it work? This might help future readers with similar problems.

**Comment by MatthewBelzer** [comment]
I just reduced dt to .0001. I don't think using the implicit and explicit methods changed it that much.
