### ISSUE TITLE
transpose() of  Tensor2Field returns error

### ISSUE THREAD

**Issue by JKrausser** [zwicker-group/py-pde#167]
Applying the transpose() methods to a Tensor2Field as 

`grid = pde.SphericalSymGrid(radius=[0, 5], shape=[100])  # generate grid
state = pde.Tensor2Field(grid, 0.1, label='Composition')
state.transpose()`

returns the error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-118-04cc0496c287> in <module>
      1 grid = pde.SphericalSymGrid(radius=[0, 5], shape=[100])  # generate grid
      2 state = pde.Tensor2Field(grid, 0.1, label='Composition')
----> 3 state.transpose()
~/Repos/py-pde/pde/fields/tensorial.py in transpose(self, label)
    362         """
    363         axes = (1, 0) + tuple(range(2, 2 + self.grid.dim))
--> 364         return Tensor2Field(self.grid, self.data.transpose(axes), label=label)
    365 
    366     def symmetrize(
ValueError: axes don't match array

**Comment by david-zwicker** [comment]
Closed by #168
