### ISSUE TITLE
Set args in method `field.plot()` to output clear pictures

### ISSUE THREAD

**Issue by lcx366** [zwicker-group/py-pde#19]
Are there any parameters in method `field.plot()` to output clear pictures for visualizing physical fields, such as dpi=200 ?

**Comment by david-zwicker** [comment]
I just updated the package to version v0.8.7 where you can simply use `field.plot(fig_style={'dpi': 200})` to achieve exactly that.

**Comment by lcx366** [comment]
Another point is that adding the color bar to figures by default, or set some parameters to customize the color bar is even better.

**Comment by david-zwicker** [comment]
I agree that the current plotting system is not optimal, but I did not want to overload it with features. The reason the colorbars are not enabled by default is that they sometimes look very weird, like in the following example:

```python
grid = UnitGrid([40, 5])
field = ScalarField.random_uniform(grid)
field.plot(colorbar=True)
```

Since I couldn't find good default values for showing colorbars, I decided to disable them by default. However, if you have a better idea, I'm happy to accept pull requests!

**Comment by lcx366** [comment]
In tools.plotting, `def add_scaled_colorbar(
    axes_image, aspect: float = 15, pad_fraction: float = 1.5, **kwargs
):` may works well.

**Comment by david-zwicker** [comment]
Sorry for not replying earlier, but I was on holidays. I looked at the new default arguments that you propose and they certainly improve the appearance for wide aspect ratio in the example above. However, in the converse case of a tall aspect ratio, e.g. when `grid = UnitGrid([5, 40])`, they lead to a worse results in my opinion. I'm not sure whether there is a better way for placing colorbars that leads to good results for all aspects ratios.

**Comment by david-zwicker** [comment]
I adjusted the `add_scaled_colorbar` method to base its size on either the width or height of the figure, whatever is larger. This seems to cover the use cases discussed above.

**Comment by david-zwicker** [comment]
We now changed the plotting of scalar fields such colorbars are shown by default, since the new method of adding scaled colorbars seems to work well. Please open a new issue if there are still problems.
