### ISSUE TITLE
Requirements for sphinx documentation

### ISSUE THREAD

**Issue by mstimberg** [zwicker-group/py-pde#2]
As part of openjournals/joss-reviews#2158 I found two minor issues with building the sphinx documentation:
* The requirements stated on https://py-pde.readthedocs.io/en/latest/getting_started.html#prerequisites do not include `sphinx-gallery`.
* The `docs/requirements.txt` file does not include `pillow`, but it seems to be necessary to generate thumbnails for the sphinx gallery.

**Comment by david-zwicker** [comment]
Thank you for the report. The documentation was indeed outdated and did not list all packages required to build the documentation. However, I did not need to install `pillow` explicitly to build the documentation. Are you seeing a specific error? Note that I'm currently having trouble with `sphinx-gallery` due to a [bug in that package](https://github.com/sphinx-gallery/sphinx-gallery/issues/634).

**Comment by mstimberg** [comment]
Earlier, I got the following error after calling `make html`:
```pytb
Exception occurred:
  File "/home/marcel/anaconda3/envs/pypde/lib/python3.7/site-packages/sphinx_gallery/utils.py", line 27, in _get_image
    % (exc,))
RuntimeError: Could not import pillow, which is required to rescale images (e.g., for thumbnails): No module named 'PIL'
```
However, I cannot reproduce the problem any more after uninstalling `pillow` or running it in a new environment without it :roll_eyes:  Please feel free to close the issue.

**Comment by david-zwicker** [comment]
This is indeed weird. However, if `sphinx-gallery` requires `pillow`, they should probably list it in their requirements. I certainly do not import it anywhere in my code directly.

**Comment by mstimberg** [comment]
Oh, silly me. I *can* reproduce it when I delete the `docs/source/examples_gallery/images/` directory (I ran `make clean` but that only deletes the `docs/build` directory). 

The `sphinx-gallery` [README file](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/README.rst) states:

> Sphinx-Gallery has also support for packages like:
> 
>     Matplotlib
>     Seaborn
>     Mayavi
> 
> For much of this functionality, you will need pillow.

So I think for `py-pde`'s documentation it indeed seems to be a dependency.

**Comment by david-zwicker** [comment]
Good catch! I added the package to `docs/requirements.txt`.
