### ISSUE TITLE
module 'sympy.core.core' has no attribute 'basic'

### ISSUE THREAD

**Issue by yishu0524** [zwicker-group/py-pde#21]
after i install the package, i try to run the example code 2.1. Plotting a vector field. i copied the code and put it into my jupyter notebook, i got this message
module 'sympy.core.core' has no attribute 'basic'

many other examples can not run, can anyone help me figure out why and solve it?

thank you very much.

**Comment by bennygit** [comment]
I am having the same error with sympy 1.5.1 installed: 

AttributeError                            Traceback (most recent call last)
<ipython-input-4-8d34e3b4fd6e> in <module>
      2 
      3 grid = CylindricalGrid(radius=3, bounds_z=[0, 4], shape=16)
----> 4 field = ScalarField.from_expression(grid, "sqrt(z) * exp(-r**2)")
      5 field.plot(title="Scalar field in cylindrical coordinates")

~/.local/lib/python3.6/site-packages/pde/fields/scalar.py in from_expression(cls, grid, expression, label)
     55                 Name of the field
     56         """
---> 57         from ..tools.expressions import ScalarExpression
     58 
     59         expr = ScalarExpression(expression=expression, signature=grid.axes)

~/.local/lib/python3.6/site-packages/pde/tools/expressions.py in <module>
     83 
     84 
---> 85 class ExpressionBase(metaclass=ABCMeta):
     86     """ abstract base class for handling expressions """
     87 

~/.local/lib/python3.6/site-packages/pde/tools/expressions.py in ExpressionBase()
     91         expression: sympy.core.basic.Basic,
     92         signature: Optional[Sequence[Union[str, List[str]]]] = None,
---> 93         user_funcs: Optional[Dict[str, Any]] = None,
     94     ):
     95         """

AttributeError: module 'sympy.core.core' has no attribute 'basic'

**Comment by david-zwicker** [comment]
I still don't understand where the error is coming from, since it works on my machine and in CI, but it's not a crucial error. I just updated the `py-pde` package to version `0.10.1`, where the `sympy.core` module would only be imported for type checking. Could you please check whether things work now?

**Comment by bennygit** [comment]
The plot_cylindrical_field.ipynb example is now running without errors! Thanks!

**Comment by david-zwicker** [comment]
This is good to hear! I'm closing this issue, but if there are more problems, feel free to open a new one.
