### ISSUE TITLE
Is there a method to extract the components of the gradient when constructing a PDE?

### ISSUE THREAD

**Issue by lcx366** [zwicker-group/py-pde#24]
Is there a method for this package to extract the components of the gradient when constructing equations with PDE class, such as `eq = PDE({'u':"-gradient_x(u))"})`? I did not find a direct way to implement it  in the document. Can you add a similar function?

**Comment by david-zwicker** [comment]
There currently is no direct method to access vector (or tensor) components. However, the master branch now has code which allows you to use a user-defined function. You could thus achieve what you want using

```python
eq = PDE({"u": "-get_x(gradient(u))"}, user_funcs={"get_x": lambda arr: arr[0]})
```

Here, `get_x` is a simple function that extracts the first component of a vector. Alternatively, you could 
This is also illustrated in [a new example](https://github.com/zwicker-group/py-pde/blob/master/examples/pde_1d_expression.py). This variant has the disadvantage that first the full gradient is calculated and then only the first component is used.

Alternatively, you may also register your own operator that only evaluates the `x`-derivative:
```python
import functools
from pde.grids.operators.cartesian import _make_derivative

make_gradient_x = functools.partial(_make_derivative, axis=0)
pde.CartesianGrid.register_operator('gradient_x', make_gradient_x)
```
If you do this, your original idea should work.

**Comment by david-zwicker** [comment]
I close this issue since there has not been any reply for 2 weeks. Please reopen if there are still problems.
