### ISSUE TITLE
Boundary conditions causing numba/numpy imcompatibility

### ISSUE THREAD

**Issue by esidebo** [zwicker-group/py-pde#28]
I'm trying to simulate a square drum, i.e. membrane vibrations by evolving the 2D wave equation.
I get the following error if I try to set the boundary to zero
```
AssertionError:
Not equal to tolerance rtol=1e-07, atol=1e-07
The numba compiled implementation of the right hand side is not compatible with the numpy implementation. This check can be disabled by setting the class attribute `check_implementation` to `False`.
Mismatched elements: 252 / 8192 (3.08%)
Max absolute difference: 0.02450429
Max relative difference: 1.0097242
 x: array([[[ 0.000000e+00,  0.000000e+00,  0.000000e+00, ...,
          0.000000e+00,  0.000000e+00,  0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00, ...,...
 y: array([[[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
          0.      ],
        [ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,...
```

If I explicitly set the `check_implementation` to `False` I can solve the equation, but what does that mean, can I trust that solution? If I remove the boundary conditions I can solve successfully.  Maybe I'm doing some mistake in my implementation, I'm not entirely sure how to interpret the boundary conditions when there are multiple fields. Can someone help? Below is my code. 
```
"""
Simulate waves on membrane fixed to square frame.
"""

import pde
from pde import WavePDE, ScalarField, UnitGrid, FieldCollection

# Square shaped membrane
grid = UnitGrid([64, 64], periodic=[False, False])
u = ScalarField.from_expression(grid, "sin(2*pi*x/64)*sin(2*pi*y/64)", label="Field $u$")
v = ScalarField(grid, label="Field $v$") 
state = FieldCollection([u, v])

# define the pde, fixed frame: boundary values = 0
eq = WavePDE(speed=0.5, bc=[[{'value':0}, {'value':0}], [{'value':0}, {'value':0}]])  

storage = pde.MemoryStorage()

trackers = [
    "progress",  # show progress bar during simulation
    "steady_state",  # abort when steady state is reached
    storage.tracker(interval=1),  # store data every simulation time unit
    pde.PlotTracker(show=True),  # show images during simulation
    # print some output every 5 real seconds:
    pde.PrintTracker(interval=pde.RealtimeIntervals(duration=2)),
]
result = eq.solve(state, 20, dt=0.01, tracker=trackers)
```

**Comment by david-zwicker** [comment]
Thank you very much for the report. Indeed, there was a bug in the code, where the boundary condition was only applied to the `numba`-compiled version and not the python version. This has been fixed in the latest version of the master branch on GitHub. Could you please check whether this fixes your problem?

**Comment by esidebo** [comment]
Yes, that worked!

**Comment by NwaObed** [comment]
I have encountered similar situation too. Can someone help please. This is my code:

s = np.sqrt(1./1000.)
drift = "0.02+0.13*x"
diffus = "0.5*0.001"

term1 = "0.13*p"
term2 = f"({drift}) * gradient(p)"
term3 = "0.0005 * laplace(p)"
eq = pde.PDE({"p": f"{term1} + {term2} + {term3}"}, bc={"value": 0})

grid = pde.CartesianGrid([[1, 5]], 64)  # generate grid
field = pde.ScalarField(grid, 1)  # generate initial condition

storage = pde.MemoryStorage()  # store intermediate information of the simulation
res = eq.solve(field, 100, dt=1e-3, tracker=storage.tracker(1))  # solve the PDE

pde.plot_kymograph(storage)  # visualize the result in a space-time plot
