### ISSUE TITLE
Installation with conda

### ISSUE THREAD

**Issue by volpatto** [zwicker-group/py-pde#29]
Hi, @david-zwicker and collaborators!

Firstly, I would like to say that `py-pde` is a really nice and well written Python package. The API is a charm. Congratulations for this work.

Well, getting back to business. Would you be interested in extending installation options with [conda](https://docs.conda.io/en/latest/)? I put `py-pde` there, using the [conda-forge](https://conda-forge.org/) channel. Instructions to install `py-pde` using `conda` is provided in [this feedstock](https://github.com/conda-forge/py-pde-feedstock).

If you have interest, I would happily open a PR updating installation instructions.

Cheers!
Diego

**Comment by david-zwicker** [comment]
Dear Diego,

this is an excellent idea, in particular since we also use conda to manage python package on our HPC system. I would very much be interested in updated installation instructions and you're also welcome to add the conda-badge and some details to the readme.

Best,
David

**Comment by volpatto** [comment]
Hi, David.

Great! So it would be enough if I submit a PR to update README and then you update the docs at your side?

**Comment by volpatto** [comment]
Ah, sorry, I almost forgot:

Would you like to be included as one of the maintainers of `py-pde` in `conda-forge` feedstock? There is no problem if you decline this invitation. It would be nice because `conda-forge` updates everything automatically and if it misses any update (in `py-pde` requirements, for instance), you are the best person to check it out.

**Comment by david-zwicker** [comment]
I merged your change, so the link to `conda` now appears in the readme of the master branch. However, I don't really know how `conda-forge` is organized. In particular, if I publish a new version on GitHub, does `conda-forge` update automatically?

**Comment by volpatto** [comment]
Great, thanks!

> However, I don't really know how conda-forge is organized. In particular, if I publish a new version on GitHub, does conda-forge update automatically?

Ah, yes! `conda-forge` tracks the package versions, then automatically updates the version provided there. It will build the new version and store it in the `conda-forge` channel. However, this procedure is not fully automatic. A conda-forge bot opens a PR in the package "feedstock" (this is where the "package recipe" is stored, a `yaml` file), updating some details there, like new dependencies and stuff like that. This is the reason why it would be really convenient to have one of the package developers as one of the feedstock maintainer as well.

**Comment by david-zwicker** [comment]
I see. Shall we try adding me as a maintainer and we'll see how it goes?

**Comment by volpatto** [comment]
Nice, I will add you there.

**Comment by david-zwicker** [comment]
I just updated `py-pde` to a new version and merged a PR on conda-forge, which seemed to have worked. Looks as if this is not too complicated after all. Thanks for your help. I'm now closing this issue since it seems to be resolved.

**Comment by volpatto** [comment]
Thanks! Well, most of the time the maintainer just has to wait for the feedstock build to pass and then merge it. If you face any problem related to `py-pde` feedstock, please feel free to ping me.
