### ISSUE TITLE
tqdm in jupyter notebook

### ISSUE THREAD

**Issue by mstimberg** [zwicker-group/py-pde#3]
[openjournals/joss-reviews#2158]

When I run the example jupyter notebooks, the tracker displaying an error bar with `tqdm` fails if `ipywidgets` is not installed.

**Comment by david-zwicker** [comment]
Thank you for the report. I feel this is more a bug of `tqdm.auto`, but I added a simple safe-guard checking for `ipywidgets` to circumvent this.
