### ISSUE TITLE
parallel solutions of 1D diffusion equation with time-variant Neumann BC determined by system of ODEs

### ISSUE THREAD

**Issue by JackElsey** [zwicker-group/py-pde#33]
Thank you for publishing this package. However, after reading through the documentation I don't think I can use it to model my system. Hopefully you can tell me I'm mistaken!

I need to model a system where a sequential reaction (e.g. compound 1 ➞ compound 2 ➞ compound 3) is occurring in the aqueous phase while the chemical compounds involved in that sequential reaction are also diffusing into a solid phase. The reaction only occurs in the aqueous phase and the solid phase is only present on one wall of the reaction vessel, so the problem involves the 1D diffusion equation. 

When there is no solid phase present I can model the system using `scipy.integrate.solve_ivp` to solve a set of ODEs describing the reaction kinetics:

![image](https://user-images.githubusercontent.com/19174587/99853526-20f1e080-2b51-11eb-87aa-af3f9cd80491.png)

where **c** is a vector of aqueous chemical concentrations.

Can this package:

1. Perform multiple solutions of the 1D diffusion equation (one for each chemical compound) in parallel?
2. Incorporate [Neumann](https://py-pde.readthedocs.io/en/latest/packages/pde.grids.boundaries.html#pde.grids.boundaries.local.NeumannBC) boundary conditions that are a determined by a system of ODEs?

**Comment by david-zwicker** [comment]
It's not completely clear to me what you're asking, but it sounds as if you want to couple different domains. If so, this is not supported by the package.

**Comment by JackElsey** [comment]
Hello David,

Thank you for your speedy reply.
