### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by hxwe** [zwicker-group/py-pde#345]
I am learing python for just one month.I still can not understand how to use the py-pde.But I have to solve a pde problem named Dual-temperature equation.So I need some advice on how to use it or where I can learn.

**Comment by david-zwicker** [comment]
We can only help you if you have a concrete question and demonstrated first attempts.

**Comment by hxwe** [comment]
Excuse me,I am still quite not sure whether it can solve heat conduction problems like this .
[heat conduction problems.docx](https://github.com/zwicker-group/py-pde/files/10213684/heat.conduction.problems.docx)
If so,how can I input the parameters.
Thanks!
