### ISSUE TITLE
Is there any way to apply constraint inside the domain, such as fix the value in the middle?

### ISSUE THREAD

**Issue by huanglz03** [zwicker-group/py-pde#36]
or apply some functions to the point in the domain?

**Comment by david-zwicker** [comment]
There is no way to constrain fields inside the domain. I don't know your use case, but I assume that the correct treatment would be to use a domain with a hole. The constraint could then be imposed at the boundary of the hole. For such complex domains, finite difference might not be a suitable approximation, so I suggest looking into some finite element or finite volume code.

However, as some workaround, you could write your own class in `py-pde` and overwrite the method `make_modify_after_step` to create a function that alters the field after every time step. In this function you could impose certain values in the field. However, this is untested, unsupported.

**Comment by huanglz03** [comment]
[j.jfluidstructs.2016.07.004.pdf](https://github.com/zwicker-group/py-pde/files/5828320/j.jfluidstructs.2016.07.004.pdf)

[pde_srinil.pdf](https://github.com/zwicker-group/py-pde/files/5828343/pde_srinil.pdf)
[global_para_srinil.pdf](https://github.com/zwicker-group/py-pde/files/5828344/global_para_srinil.pdf)

When I use py-pde to simulate the model presented in the literature(equation 1,2,3,9,12-16), it seems very hard to converge, could you help me to find that is there something wrong in my code?

**Comment by david-zwicker** [comment]
I'm sorry, but I don't have the time to help you with implementing specific equations.

**Comment by huanglz03** [comment]
Ok, Thanks anyway!
