### ISSUE TITLE
Trouble with website search functionality

### ISSUE THREAD

**Issue by Benj-Ward** [zwicker-group/py-pde#385]
As per title, I am having trouble with the search functionality of the website for py-pde documentation. Any search will trigger the searching..., but no results are ever pulled successfully by the search engine. I want to see if this is a common problem or an issue on my end.

The URL: https://py-pde.readthedocs.io/en/latest/search.html?q=installing+using+pip&check_keywords=yes&area=default

**Comment by david-zwicker** [comment]
Thank you for reporting this. I can reproduce the error and will investigate. As a work-around, you can try to create the documentation locally, where the search function should then work.

**Comment by david-zwicker** [comment]
Closed by #386
