### ISSUE TITLE
Moving boundary conditions

### ISSUE THREAD

**Issue by ChengXiaoSi** [zwicker-group/py-pde#391]
Hello! I want to know how do I set my boundary conditions if they are moving over time.
Thanks!

**Comment by david-zwicker** [comment]
I don't know what you specific problem is, but there is [an example with time-dependent boundary conditions](https://py-pde.readthedocs.io/en/latest/examples_gallery/time_dependent_bcs.html#sphx-glr-examples-gallery-time-dependent-bcs-py), which might help you.

**Comment by ChengXiaoSi** [comment]
Thank you very much for your reply！The problem I encountered was a bit complicated. The solution domain is divided into two parts, each separately governed by a different PDE, and these two PDEs are coupled through a common boundary condition.And the two boundary conditions of the solution domain expand with time at a fixed rate, which is the moving boundary condition I mentioned earlier.I don't know whether py-pde can solve such a problem.Thanks!

**Comment by david-zwicker** [comment]
I‘m afraid that this is not easily possible and we also don’t have plans to implement anything along these lines. Sorry

**Comment by ChengXiaoSi** [comment]
Thanks for your answer! I'll try something else.
