### ISSUE TITLE
Suggestion: test dependencies

### ISSUE THREAD

**Issue by mstimberg** [zwicker-group/py-pde#4]
[openjournals/joss-reviews#2158]

For consistency, I'd suggest mentioning the dependencies for running tests already on the [Getting Started](https://py-pde.readthedocs.io/en/latest/getting_started.html#prerequisites) page of the documentation (in the same way as for the documentation dependencies).

Given that "nobody reads the documentation", you might also want to consider a check for the presence of `pytest` etc. directly in the shell scripts with a helpful error message for the user. For example, if the user does not have `pytest-xdist` installed, running `tests_parallel.sh` will currently fail with "unknown option -n".

**Comment by david-zwicker** [comment]
Thank you for the suggestion. I added a `requirements.txt` to the `tests` directory, which hopefully helps with setting up a suitable test environment. I also now mention this file and the one in the `docs` folder in the documentation.
