### ISSUE TITLE
Warning message seems a bit confusing

### ISSUE THREAD

**Issue by HannoSpreeuw** [zwicker-group/py-pde#448]
I got a bit puzzled by [this warning message](https://github.com/zwicker-group/py-pde/blob/1441e20a8ec035c7d27961570de25a1fb6902c92/pde/fields/base.py#L1648):
```
"`apply_operator` is deprecated. Use `apply_operator` instead"
```
What is meant is probably:
```
"`_apply_operator` is deprecated. Use `apply_operator` instead"
```

**Comment by david-zwicker** [comment]
Good point! This is certainly a typo in the warning. I'll correct it soon. Thanks for reporting!
