### ISSUE TITLE
Implement time dependent Robin boundary conditions

### ISSUE THREAD

**Issue by jAniceto** [zwicker-group/py-pde#465]
Time dependent Robin boundary conditions are common in multiple chemical engineering applications, namely when modeling adsorption and chromatographic separation processes. 

Adding this to py-pde would be quite useful.

Discussed in https://github.com/zwicker-group/py-pde/discussions/461.

**Comment by david-zwicker** [comment]
Very good timing – #464 already addresses this issue :)

**Comment by david-zwicker** [comment]
PR #464 has now been merged, closing this issues.

**Comment by jAniceto** [comment]
That was quick. :D Thanks.
