### ISSUE TITLE
Conflict of keyword method in kwargs of PDEBase.solver

### ISSUE THREAD

**Issue by Cluckenstein** [zwicker-group/py-pde#475]
Team,
I have noticed, that if one is to use the `solve ` function with the` solver = ScipySolver`, then the kwargs are forwarded to the ScipySolver, but the solver can use the keyword `method ` to define which scipy solver is to be used. However in pde/pdes/base.py line 601 the kwarg key method is poped because of depreciation. Unfortunatly I cannot do a Pull request, thank you for all the work here !

**Comment by david-zwicker** [comment]
Thanks for the report – I added a quick fix to the `master` branch that should only warn if the `solver` argument is not set.
