### ISSUE TITLE
Suggestion: add CI for Windows/OS X

### ISSUE THREAD

**Issue by mstimberg** [zwicker-group/py-pde#5]
[openjournals/joss-reviews#2158]

The documentation states "The code is tested under Linux, Windows, and macOS", but the repository currently only runs the test suite on Linux via Travis. Travis also supports testing under OS X, and there are other (free for FOSS) services like https://www.appveyor.com/ or https://azure.microsoft.com/en-us/services/devops/pipelines/ that test across all three OS.

**Comment by david-zwicker** [comment]
I use github Actions to run the tests under macOS, windows, and linux. I haven't created a badge for this, since I don't want too many badges in the readme.

**Comment by mstimberg** [comment]
Ah, great! Sorry I overlooked this.
