### ISSUE TITLE
 Time-dependent boundary conditions 

### ISSUE THREAD

**Issue by engsbk** [zwicker-group/py-pde#53]
Thanks for the very beneficial code. I'm actually using it as one of my base stones in my research!

I 'm trying to implement the wave equation with a time-dependent source placed at the boundary.
```

speed = 0.01
frequency = 10
source = f"sin(pi*x) * exp(-2*pi*{frequency}*t)"
eq = PDE(
    {
        "u": f"v",
        "v": f"{speed}**2 * laplace(u) " 
    }, bc=[{"value": f"sin(pi*x) * exp(-2*pi*{frequency}*t)"}, {"derivative":0}]
)
```
but I get this error:

```
 f"Arguments {args} were not defined in expression signature {signature}"
RuntimeError: Arguments {'t'} were not defined in expression signature ['x']
```

It will be a novel addition to your code if it becomes supported!

Thanks again.

**Comment by david-zwicker** [comment]
I briefly looked into this, but I'm afraid that this is not possible with the current infrastructure of handling boundary conditions. I have vague plans to restructure the boundary conditions completely, but I don't think I will find time for this anytime soon.

**Comment by Jianxun-Wang** [comment]
It's a very nice FD implementation, but it will be great to support time-dependent BC.

**Comment by david-zwicker** [comment]
I agree that it would be a nice feature, but it is not easy to include using the current framework. This is because the boundary conditions are currently implemented for operators, which do not have any notion of time. I'd be happy to discuss ways how to remove this limitation, but I likely won't have time to include it myself anytime soon.

**Comment by Jianxun-Wang** [comment]
Sure, understood. Maybe we could also think if there is a good way to remove this limitation, but it seems not very easy. Anyway, thanks for sharing!

**Comment by david-zwicker** [comment]
The newest version `0.17` now supports time-dependent boundary conditions in some special circumstances. See the [example](https://github.com/zwicker-group/py-pde/blob/master/examples/time_dependent_bcs.py) for a demonstration.

**Comment by spears9** [comment]
Time-dependent BCs are a great addition, but the example fails.  Something I'm missing?

` from time_dependent_bcs import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spears9/python/time_dependent_bcs.py", line 17, in <module>
    eq.solve(state, t_range=20, dt=1e-4, tracker=storage.tracker(0.1))
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/pdes/base.py", line 426, in solve
    final_state = controller.run(state, dt)
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/solvers/controller.py", line 148, in run
    stepper = self.solver.make_stepper(state=state, dt=dt)
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/solvers/explicit.py", line 190, in make_stepper
    inner_stepper = self._make_euler_stepper(state, dt)
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/solvers/explicit.py", line 89, in _make_euler_stepper
    rhs_pde = self._make_pde_rhs(state, backend=self.backend)
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/solvers/base.py", line 118, in _make_pde_rhs
    rhs = self.pde.make_pde_rhs(state, backend=backend)
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/pdes/base.py", line 155, in make_pde_rhs
    rhs_numpy = self.evolution_rate(state.copy(), 0).data
  File "/Users/spears9/Library/Python/3.6/lib/python/site-packages/pde/pdes/pde.py", line 376, in evolution_rate
    return state.copy(data=rhs(state.data, t))
  File "<lambdifygenerated-2>", line 2, in _lambdifygenerated
NameError: name 'laplace' is not defined`

**Comment by david-zwicker** [comment]
The example `time_dependent_bcs.py` runs on my computer. Could you please specify the code you're running and format the error you're getting, so I can investigate? It would also be helpful if you could report the outcome of running `scripts/show_environment.py`, so I get a better idea of your setup.
